[project]
name = "builder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.6"
dependencies = [
    "psbuilder@git+https://github.com/PythonSwiftLink/PSBuilder@master"
]
