# This workflow will build a KivySwiftLink release

name: Build Components with UV


on:

  # workflow_dispatch:
  #   inputs:
  #     tag:
  #       description: 'input new release tag'
  #       required: false
  #       type: string
  #       default: "311.0.0"
  #     lastest:
  #       description: 'lastest release?'
  #       required: false
  #       type: boolean
  #       default: false

  workflow_call:
    inputs:
      tag:
        required: false
        type: string
        default: "311.0.0"
      lastest:
        required: false
        type: boolean
        default: false

jobs:
  toolchainBuild:
    runs-on: macOS-14
    #runs-on: self-hosted
    permissions:
        contents: write
  
    steps:
    #   - uses: maxim-lobanov/setup-xcode@v1
    #     with:
    #       xcode-version: '15.0'
        
      - uses: actions/checkout@v4
      
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # install the python version needed
      
      - name: brew install uv
        run: brew install uv
      
      # - name: clone psbuilder
      #   run: git clone https://github.com/PythonSwiftLink/PSBuilder
      
      - name: uv sync builder
        run: uv sync --no-editable -v
        working-directory: builder

      # - name: builder generate all
      #   run: uv run generate_all.py ${{ github.event.inputs.tag }}
      #   working-directory: builder

      - name: build hostpython
        run: uv run -v build.py hostpython3
        working-directory: builder

      - name: build freetype
        run: uv run -v build.py freetype
        working-directory: builder

      - name: build libpng
        run: uv run -v build.py libpng
        working-directory: builder

      - name: build libjpeg
        run: uv run -v build.py libjpeg
        working-directory: builder

      - name: build python3
        run: uv run -v build.py python3
        working-directory: builder

      - name: build kivy
        run: uv run -v build.py kivy
        working-directory: builder

      - name: build pillow
        run: uv run -v build.py pillow
        working-directory: builder

      - name: build numpy
        run: uv run -v build.py numpy
        working-directory: builder
      
      - name: swift_package all
        run: uv run -v generate_all.py ${{ github.event.inputs.tag }}
        working-directory: builder
      
      - name: show root files before uploads
        run: ls
        working-directory: builder

      - uses: actions/upload-artifact@v4
        with:
          name: release-output
          path: builder/swift_packages

  # ###############################################################################
  # ###############################################################################
  # ###############################################################################
  # #moving next part to an ubuntu machine
