# This workflow will build a KivySwiftLink release

name: release builder


on:

  workflow_dispatch:
    inputs:
      tag:
        description: 'input new release tag'
        required: true
        type: string




jobs:
  toolchainBuild:
    runs-on: macOS-13
    # runs-on: self-hosted
    permissions:
        contents: write
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0'
        
      - uses: actions/checkout@v4
      
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install kivy-ios
        run: |
          python3 -m pip install --upgrade pip
          pip3 install https://github.com/kivy/kivy-ios/archive/master.zip
          #brew install autoconf automake libtool pkg-config
          #brew link libtool
          
          chmod 755 restructure.sh
          mkdir kivy_build
      # cd into kivy_build folder and running toolchain build python3, kivy, pillow 
      - name: toolchain build python3 kivy pillow
        run: |
          cd kivy_build 
          toolchain build python3 kivy pillow

      # pulling out necessary libraries and zipping them into "output" folder
      - name: repack build environment
        #run: ./restructure.sh
        run: |
          mkdir output
          cp -rf kivy_build/dist/xcframework output/
          cp -rf kivy_build/dist/root/python3/include/python3.10 output/xcframework/libpython3.10.xcframework/ios-arm64/
          cp -rf kivy_build/dist/root/python3/include/python3.10 output/xcframework/libpython3.10.xcframework/ios-x86_64-simulator/
          cp -f PythonXc_Info.plist output/xcframework/libpython3.10.xcframework/Info.plist
          cp -f create_package.sh output/
          
          mv kivy_build/dist/root/python3/lib python_lib
          zip -r python_lib.zip python_lib
          mv kivy_build/dist/lib dist_lib
          zip -r dist_lib.zip dist_lib
          mv -f python_lib.zip output/
          mv -f dist_lib.zip output/
          
          cd output/xcframework
          
          for FILE in *; 
              do 
                  filename="$FILE"
                  echo $filename
                  zip -r "${filename%.*}".zip $FILE
                  rm -rf $FILE
              done
          
      # uploading "output" folder for the next task to use. (ubuntu machine)
      - uses: actions/upload-artifact@v3
        with:
          name: kivy-output
          path: ./output
  
  # moving next part to an ubuntu machine
  create_package:
    name: Create Package
    runs-on: ubuntu-latest
    needs: [toolchainBuild]

    steps:
      - uses: actions/checkout@v4
        # with:
        #   repository: pythonswiftlink/KivySwiftLink
      - uses: actions/download-artifact@v3
        with:
          name: kivy-output
      - run: |
          
          mkdir KivySwiftLink
          git clone https://github.com/PythonSwiftLink/PythonSwiftLink

          cp -rf PythonSwiftLink/Sources KivySwiftLink/
          cp -rf xcframework KivySwiftLink/Sources/PythonLib/
          cp -f Package.swift KivySwiftLink
          cp -rf KivyLauncher KivySwiftLink/Sources/KivyLauncher
      
      # commit new package to kivyswiftlink/master
      - name: Push to master
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.Homebrew }}
        with:
          source-directory: 'KivySwiftLink'
          destination-github-username: 'pythonswiftlink'
          destination-repository-name: 'kivyswiftlink'
          user-email: pythonswiftlink@gmail.com
          target-branch: master
      
      # create a new release from master and python_lib.zip / dist_lib.zip to the release
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "python_lib.zip, dist_lib.zip"
          tag: ${{ github.event.inputs.tag }}
          repo: KivySwiftLink
          token: ${{ secrets.Homebrew }}
          allowUpdates: true
