# This workflow will build a KivySwiftLink release

name: Build Components


on:

  # workflow_dispatch:
  #   inputs:
  #     tag:
  #       description: 'input new release tag'
  #       required: false
  #       type: string
  #       default: "311.0.0"
  #     lastest:
  #       description: 'lastest release?'
  #       required: false
  #       type: boolean
  #       default: false

  workflow_call:
    inputs:
      tag:
        required: false
        type: string
        default: "311.0.0"
      lastest:
        required: false
        type: boolean
        default: false

jobs:
  toolchainBuild:
    runs-on: macOS-13
    #runs-on: self-hosted
    permissions:
        contents: write
  
    steps:
    #   - uses: maxim-lobanov/setup-xcode@v1
    #     with:
    #       xcode-version: '15.0'
        
      - uses: actions/checkout@v4
      
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # install the python version needed
      
      # - name: brew installs
      #   run: |
      #     brew tap PythonSwiftLink/tools
      #     brew install swiftpackagegen
      
      # - name: chmod tools
      #   run: |
      #     chmod 755 tools/SwiftPackageGen
      #     chmod 755 tools/PSProject
      
      - name: pip installs
        run: |
          pip3.11 install https://github.com/kivyswiftlink/PSL_Toolchain/archive/refs/heads/master.zip 
      # - name: install kivy-ios
      #   uses: kivyswiftlink/actions/install_kivy_ios@master

      #### build phase ####
      
      - name: build all
        run: psl_toolchain swiftpackage all

      
      - uses: actions/upload-artifact@v4
        with:
          name: release-output
          path: ./swiftpackages

  # ###############################################################################
  # ###############################################################################
  # ###############################################################################
  # #moving next part to an ubuntu machine
