# This workflow will build a KivySwiftLink release

name: local_builder_tester


on:

  workflow_dispatch:
    inputs:
      tag:
        description: 'input new release tag'
        required: true
        type: string
      lastest:
        description: 'lastest release?'
        required: false
        type: boolean
        default: false

jobs:
  toolchainBuild:
    #runs-on: macOS-13
    runs-on: self-hosted
    permissions:
        contents: write
  
    steps:
    #   - uses: maxim-lobanov/setup-xcode@v1
    #     with:
    #       xcode-version: '15.0'
        
      - uses: actions/checkout@v4
      
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # install the python version needed
      
      # - name: brew installs
      #   run: |
      #     brew tap PythonSwiftLink/tools
      #     brew install swiftpackagegen
      
      # - name: chmod tools
      #   run: |
      #     chmod 755 tools/SwiftPackageGen
      #     chmod 755 tools/PSProject
      
      - name: install kivy-ios
        uses: kivyswiftlink/actions/install_kivy_ios@master

      #### build phase ####
      
      - name: build hostpython3
        run: toolchain build hostpython3
      - name: build python3
        run: |
          toolchain build python3
          swift run --package-path KivyBuilder KivyBuilder toolchain python3

      - name: build kivy
        run: |
            toolchain build kivy
            swift run --package-path KivyBuilder KivyBuilder toolchain kivy

      - name: build pillow
        run: |
            toolchain build pillow
            swift run --package-path KivyBuilder KivyBuilder toolchain pillow
      
      - name: build numpy
        run: |
          toolchain build numpy
          swift run --package-path KivyBuilder KivyBuilder toolchain numpy

      - name: build kiwisolver
        run: |
            toolchain build kiwisolver
            swift run --package-path KivyBuilder KivyBuilder toolchain kiwisolver

      - name: build materialyoucolor
        run: |
            toolchain build materialyoucolor
            swift run --package-path KivyBuilder KivyBuilder toolchain materialyoucolor

      - name: build matplotlib
        run: |
            toolchain build matplotlib
            swift run --package-path KivyBuilder KivyBuilder toolchain matplotlib

      - name: build ffmpeg
        run: |
            toolchain build ffmpeg
            swift run --package-path KivyBuilder KivyBuilder toolchain ffmpeg

      - name: build ffpyplayer
        run: |
            toolchain build ffpyplayer
            swift run --package-path KivyBuilder KivyBuilder toolchain ffpyplayer
      
      

      - name: KivyBuilder repack
        run: swift run --package-path KivyBuilder KivyBuilder repack
      
      
      - name: zip dists content
        uses: kivyswiftlink/actions/zip_dist_folder@master


      ## zip xcframeworks
      - name: zip all xcframeworks
        uses: kivyswiftlink/actions/zip_all_xcframeworks@master

      - name: update Python package.swift
        run: |
          SwiftPackageGen generate \
            ./package_templates/KivyPythonCore.yml \
            ${{ github.event.inputs.tag }} \
            --output output/python3/Package.swift
      
      - name: update Kivy package.swift
        run: |
          SwiftPackageGen generate \
            ./package_templates/KivyCore.yml \
            ${{ github.event.inputs.tag }} \
            --output output/kivy/Package.swiftls
            

      - name: update Numpy package.swift
        run: |
          SwiftPackageGen generate \
            ./package_templates/KivyNumpy.yml \
            ${{ github.event.inputs.tag }} \
            --output output/numpy/Package.swift  

      - name: update KivyExtraPackage package.swift
        run: |
          mkdir -pv output/kivyextra
          SwiftPackageGen generate \
            ./package_templates/kivyextra.yml \
            ${{ github.event.inputs.tag }} \
            --output output/kivyextra/Package.swift  


  ###############################################################################
  ###############################################################################
  ###############################################################################
  #moving next part to an ubuntu machine
  create_package:
    name: Release Packages
    runs-on: ubuntu-latest
    needs: [toolchainBuild]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/download-artifact@v3
        with:
          name: release-output

      - name: zip dists content
        uses: kivyswiftlink/actions/release_packages@master