name: Build Components


on:

  workflow_dispatch:
    inputs:
      tag:
        description: 'input new release tag'
        required: false
        type: string
        default: "311.0.0"
      lastest:
        description: 'lastest release?'
        required: false
        type: boolean
        default: false


jobs:
    build_components:
        uses: "./.github/workflows/build_components.yml"
        with:
          tag: ${{ github.event.inputs.tag }}
          lastest: ${{ github.event.inputs.lastest }}
    release_components:
        uses: "./.github/workflows/release_components.yml"
        with:
          tag: ${{ github.event.inputs.tag }}
          lastest: ${{ github.event.inputs.lastest }}
    